### ISSUE TITLE
How can I use byebug?

### ISSUE THREAD

**Issue by boobooninja** [rodreegez/powder#124]
I'm still learning and have my routes setup for api.domain.com and powder / pow works great along with postman for checking them.

I haven't been able to figure out how to use byebug with this configuration. I really love byebug as I can dig in as see what is going wrong.

Any help is appreciated.

**Comment by jkotchoff** [comment]
There is a guide for this at:
[http://blog.honeybadger.io/remote-debugging-with-byebug-rails-and-pow/](http://blog.honeybadger.io/remote-debugging-with-byebug-rails-and-pow/)

**Comment by boobooninja** [comment]
@jkotchoff Thanks for that info.
